services:
  api:
    build: .
    container_name: racecalendar-dev
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./public:/app/public
    environment:
      - APP_LOG_LEVEL=DEBUG
    # Sobrescribimos el CMD del Dockerfile para activar el modo reload
    command: uvicorn src.api:app --host 0.0.0.0 --port 8080 --reload